---
- include: build-pkgs.yml
  vars:
    pkg:
      - {
          name: "ckanext-s3filestore",
          repo: "https://github.com/GSA/ckanext-s3filestore",
          requirements: "requirements.txt"
        }
  tags: ['s3filestore']

- name: add s3filestore to production.ini plugins
  replace:
    dest: /etc/ckan/production.ini
    regexp: '^(ckan.plugins(?!.*\bs3filestore\b).*)$'
    replace: '\1 s3filestore'
  tags: ['s3filestore']

- name: copy datajson export map
  copy:
    src: "{{ virtualenv }}/src/ckanext-datajson/ckanext/datajson/export_map/export.inventory.map.sample.json"
    dest: "{{ virtualenv }}/src/ckanext-datajson/ckanext/datajson/export_map/export.map.json"
    remote_src: true

- name: "Datapusher json content-type temp fix (content-type: application/json does not work now)"
  replace:
    dest: /usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py
    regexp: 'application/json'
    replace: 'application/x-www-form-urlencoded'

- name: "Datapusher https to http temp fix (local https is unreachable now)"
  replace:
    dest: /usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py
    regexp: 'result_url,'
    replace: "result_url.replace('https://','http://'),"

- name: "Remove compiled web.pyc"
  file:
    path: /usr/lib/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.pyc
    state: absent

- name: Restart apache2 one more time
  service: name=apache2 state=restarted enabled=yes