---
- name: make sure packages are installed
  action: apt pkg={{item}} state=installed update_cache=yes
  with_items:
    - python-psycopg2

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Check whether new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p

- name: Create rollback code
  command: "mv {{ project_source_new_code_path }} {{ project_source_rollback_path }}"
  when: p.stat.isdir is defined and p.stat.isdir

- name: Symlink current dir with rollback code
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ current_source_symlink }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Remove new code
  file: path="{{ project_source_new_code_path }}" state=absent

- include: build-pkgs.yml
  vars:
    pkg: "{{ ckan_pkgs }}"
    virtualenv: "{{ project_source_new_code_path }}"

- name: Remove old datapusher code
  file: path="{{ datapusher_virtual_env }}" state=absent

- include: build-pkgs.yml
  vars:
    pkg: "{{ datapusher_pkgs }}"
    virtualenv: "{{ datapusher_virtual_env }}"

- name: fix "{{ datapusher_virtual_env }}" permissions
  file: path={{ item }} state=directory group=www-data recurse=yes
  with_items:
    - "{{ datapusher_virtual_env }}"

- name: remove psycopg2
  action: pip name=psycopg2 virtualenv="{{ project_source_new_code_path }}" state=absent

- name: create directories
  action: file path={{item}} state=directory owner="www-data" group="www-data" mode=0755
  with_items:
    - /var/lib/ckan

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/ckan/who.ini
    - etc/ckan/apache.wsgi
    - etc/ckan/datapusher.wsgi
    - etc/apache2/sites-enabled/ckan.conf
    - etc/apache2/sites-enabled/datapusher.conf

- name: Configure production.ini
  template: src=templates/{{item}} dest=/{{item}}
  with_items:
    - etc/ckan/production.ini
    - etc/ckan/datapusher_settings.py

- include: additional-tasks.yml
  virtualenv: "{{ project_source_new_code_path }}"

- name: Symlink current dir with new code
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ current_source_symlink }}"
    state: link

- name: restart apache
  action: service name=apache2 state=restarted

- name: point site_url in /etc/hosts to localhost
  action: lineinfile dest=/etc/hosts line="127.0.0.1 {{ ckan_site_domain | regex_replace('https?\://','') }}"
