---
- name: make sure packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - libapache2-modsecurity

- name: default apache removed
  action: file path=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Apache | Enable some required modules
  action: command a2enmod rewrite headers remoteip
  tags:
    - common
    - skip_ansible_lint

- name: Apache | Enable Web Application Firewall
  action: command a2enmod security2
  tags:
    - web_application_firewall
    - CM-7
    - SC-7
    - SI-10
    - skip_ansible_lint

- name: Configure mod_remoteip
  template: src=templates/etc/apache2/conf-enabled/mod_remoteip.conf dest=/etc/apache2/conf-enabled/mod_remoteip.conf

- name: Apache ServerTokens Prod
  lineinfile:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: '^ServerTokens '
    line: 'ServerTokens Prod'

- name: Apache ServerSignature Off
  lineinfile:
    dest: /etc/apache2/conf-enabled/security.conf
    regexp: '^ServerSignature '
    line: 'ServerSignature Off'
