source 'https://rubygems.org'

gem 'test-kitchen', '~> 1.0'
gem 'kitchen-ansible'
gem 'kitchen-docker'
gem 'kitchen-sync'
gem 'kitchen-vagrant'
gem 'kitchen-inspec'
gem 'kitchen-transport-rsync'
gem 'kitchen-sharedtests', '~> 0.2.0'
gem 'vagrant-hostmanager', '~> 1.8', '>= 1.8.2'
