---
- name: prepare packages needed for harvester
  action: apt pkg={{item}} state=installed
  with_items:
    - default-jdk
    - tomcat6

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}} mode=0644
  with_items:
    - etc/cron.d/clean-tmp-files
    - var/lib/tomcat6/webapps/fgdc2iso.war

- name: copy saxon-license.lic
  action: template src={{item}} dest=/{{item}} mode=0644
  with_items:
    - etc/saxon-license.lic
