---

# spaghetti js fix
- name: set env
  set_fact:
    current_env: "{{ inventory_dir | basename }}"

- name: copy spaghetti to /tmp folder
  copy:
    src: js.tgz
    dest: /tmp/js.tgz
  when: (inventory_hostname != "catalogpub-web1p.prod-ocsit.bsp.gsa.gov") and (current_env == "production")

- name: make plate of spaghetti
  shell: cd /tmp && tar -xf /tmp/js.tgz -C /
  when: (inventory_hostname != "catalogpub-web1p.prod-ocsit.bsp.gsa.gov") and (current_env == "production")
