---
- name: make sure saml dependency packages are installed
  action: apt pkg={{item}} state=installed
  with_items:
    - memcached
    - m2crypto
    - xmlsec1
    - swig

- name: add saml2 to production.ini plugins
  replace:
    dest: /etc/ckan/production.ini
    regexp: '^(ckan.plugins(?!.*\bsaml2\b).*)$'
    replace: '\1 saml2'

- name: get code
  git: repo={{item.repo}} dest={{ project_source_new_code_path }}/src/{{item.name}} version={{item.branch|default('master')}}
  with_items: "{{ saml2_pkgs }}"

- name: run setup
  command: chdir={{ project_source_new_code_path }}/src/{{item.name}}/ ../../bin/python setup.py develop
  with_items: "{{ saml2_pkgs }}"
  tags: skip_ansible_lint

- name: create directories
  action: file path=/etc/ckan/saml2/ state=directory mode=0755

- name: copy all needed files
  action: copy src=etc/ckan/saml2/ dest=/etc/ckan/saml2/

- name: template all needed files
  action: template src=etc/ckan/{{item}} dest=/etc/ckan/{{item}}
  with_items:
    - saml2/pki/mycert.pem
    - saml2/pki/mykey.pem
    - who.ini

- name: Downloads idp metadata
  get_url:
    url: "{{ saml2_idp_metadata_url }}"
    dest: /etc/ckan/saml2/idp.xml
    mode: 0644
