---

- name: Remove old rollback code
  file: path="{{ project_source_rollback_path }}" state=absent

- name: Check whether new code dir exists
  stat: path="{{ project_source_new_code_path }}"
  register: p

- name: Create rollback code
  command: cp -r "{{ project_source_new_code_path }}" "{{ project_source_rollback_path }}"
  when: p.stat.isdir is defined and p.stat.isdir
  tags: skip_ansible_lint

- name: Symlink current dir with rollback code
  file:
    src: "{{ project_source_rollback_path }}"
    path: "{{ current_source_symlink }}"
    state: link
  when: p.stat.isdir is defined and p.stat.isdir

- name: Remove new code
  file: path="{{ project_source_new_code_path }}" state=absent

- name: Clone CKAN app
  git: repo="{{ app_repo }}" dest="{{ app_source_path }}" version=master

- name: Install CKAN app
  command: sh install.sh "{{ project_source_new_code_path }}" chdir={{ app_source_path }}
  tags: skip_ansible_lint

# Configure CKAN
- name: Configure production.ini
  template: src=templates/{{ item }}.j2 dest=/{{ item }}
  with_items:
    - etc/ckan/production.ini

# Add token.dat file
- name: Add token.dat file
  copy:
    content="{{ token_dat }}"
    dest=/etc/ckan/token.dat

- name: Configure who.ini
  copy: src={{ app_source_path }}/config/environments/{{ env }}/saml2/who.ini dest=/etc/ckan remote_src=True

- name: Upgrade repoze.who to 2.0 for local env
  pip: name=repoze.who version=2.0 virtualenv="{{project_source_new_code_path }}"
  when: env == "local"

- name: point site_url in /etc/hosts to localhost
  action: lineinfile dest=/etc/hosts line="127.0.0.1 {{ ckan_site_domain | regex_replace('https?\://','') }}"

- name: Symlink current dir with new code
  file:
    src: "{{ project_source_new_code_path }}"
    path: "{{ current_source_symlink }}"
    state: link

- name: Copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/ckan/apache.wsgi
  tags: ['frontend', 'apache']

- name: Configure ckan.conf
  template: src=templates/etc/apache2/sites-enabled/ckan.{{readwrite_type|default('default')}}.conf.j2 dest=/etc/apache2/sites-enabled/ckan.conf
  tags: ['frontend', 'apache']

- name: Restart apache
  service: name=apache2 state=restarted
  tags: ['frontend', 'apache']
