---
- name: create ckan config dir
  action: file path=/etc/ckan state=directory follow=yes

- name: copy executables
  action: copy src={{item}} dest=/{{item}} mode=0744
  with_items:
    - usr/bin/ckan

- name: copy all needed files
  action: copy src={{item}} dest=/{{item}}
  with_items:
    - etc/cron.daily/remove_old_sessions
  tags: ['cron']
