- name: Initialize ckan db
  command: ckan db init
  tags: skip_ansible_lint

- name: Initialize ckan report db
  command: ckan --plugin=ckanext-report report initdb
  tags: skip_ansible_lint

- name: Initialize ckan ga-report db
  command: ckan --plugin=ckanext-ga-report initdb
  tags: skip_ansible_lint

- name: Initialize ckan archiver db
  command: ckan --plugin=ckanext-archiver archiver init
  tags: skip_ansible_lint

- name: Initialize ckan qa db
  command: ckan --plugin=ckanext-qa qa init
  tags: skip_ansible_lint